### PR TITLE
#2 Adding ability to view images in a slideshow-style viewer

### PR DESCRIPTION
**Pull request by jbolster**
Fixing issue #2 (Enable option to show one image at a time).

I've done this in a slideshow type style.

* Press Esc to toggle viewer (or click link)
* Left / Right arrow keys to navigate
* Main page kept in sync with what's on the viewer
* Nice little by-product is that fusks can now be navigated by keyboard too.

### CODE REVIEW

**Comment by jbolster** [comment]
No activity for months on this repo and in short time I spend coding this, you've gone and changed it! ;)

Getting me used to git-rebasing, at least...

**Comment by DanAtkinson** [comment]
Well bugger me! I've gone and made some further changes to 'save' fusks and did some refactoring of the images.js file as well. I think I'll merge your changes in and then manage the conflicts locally before I push once more.

**Comment by DanAtkinson** [comment]
It seems to throw an error if you press left/right on the gallery itself. Appears to be because `currentSelectedImage` is null.

**Comment by DanAtkinson** [comment]
Also tries to load /Html/undefined at the end of the viewer. :)

**Comment by DanAtkinson** [comment]
Hi @jbolster ,

I've just checked and you're already a collaborator (along with @oliverpicton), so you should be able to automatically approve the pull requests.

Is it possible for you to rebase, resolve the above issues and recommit them?

Many thanks!

Dan

**Comment by jbolster** [comment]
My bad! That's what I get for 3am pull requests ;)

I will attempt to work out git and see what I can do.

Cheers - I knew I was collaborator but figured it was a new feature so wasn't sure if it was approve-worthy :)

**Comment by jbolster** [comment]
@DanAtkinson Not sure your merge went correctly: 7f974bed83e96f47477b208970206228b972db56 has the html and styles, but the images.js file wasn't merged. Was this not staged?

I can always redo it if it got lost in a merge.

**Comment by DanAtkinson** [comment]
Hi @jbolster, I've merged your changes in now. I was looking to move to AngularJS, but the more time I spent looking at it and fixing issues, the more I realised I was trying to overcomplicate something fairly simple.

Thanks, Dan

**Comment by jbolster** [comment]
At first I was thinking 'But nooooo! The bug' and then realised you sorted that before you pushed.

Hurrah!

**Comment by DanAtkinson** [comment]
Yeah, update the extension (it'll probably ask you to re-enable due to the new download permission) and try it out!

**Pull request merged**
