### PR TITLE
Adding download by zip

### PR DESCRIPTION
**Pull request by jbolster**
I'm adding this as a separate link with the existing download functionality in place.

Not sure if we would want to replace it or just have it separate so the user can do both.

One thing I can see with this is it doesn't user Chrome's downloadItem. We probably could by creating an objectUrl of the blob, but the included Polyfill seems to do the job nicely :)

I've included in a description text file but we can always ditch that.

### CODE REVIEW

**Comment by jbolster** [comment]
Hold on with this... it stopped working...

**Comment by jbolster** [comment]
This is what I get for trying to have a tidy commit history!

All fixed and working

**Comment by DanAtkinson** [comment]
Cool beans! :+1:  Feel free to merge when you want. :)

**Comment by DanAtkinson** [comment]
Also, please could you add the licence info for the FileSaver.js?

It's on the unminified version but not the minified one.

Thanks!

https://raw.githubusercontent.com/eligrey/FileSaver.js/master/FileSaver.js

**Comment by jbolster** [comment]
Done!

**Pull request merged**
