### PR TITLE
Rewriting Fuskr to use Angular on the options/images pages

### PR DESCRIPTION
**Pull request by jbolster**
Figure it's in a decent enough state for a PR.

From a user point of view, there haven't been many changes:
* Slideshow has a close button (and some minor changes to navigation)
* Fusk page looks a bit neater with the info box, links only show if applicable
* Selected conflict option on 'download' gets remembered

From a dev view, I think it makes it a bit nicer to work with the HTML templates and models. Routing and controllers mean it's a bit easier and tidier to expand upon :)

### CODE REVIEW

**Comment by jbolster** [comment]
So, one thing I noticed was the 'Save Fusks' was commented out (417be65a12a57cbcbdf85862ec016cf17b7272e4), so I didn't include that in the new code.

**Comment by DanAtkinson** [comment]
Hi Jonny. I'm happy for you to commit and accept the pull, but it seems like there are some conflicts to be resolved.

Thanks!

**Comment by jbolster** [comment]
Oops! Must be when I merged the other fix, forgot to update this. Will fix
that.

**Comment by jbolster** [comment]
Weirdly, the commit to fix the merge conflict had zero changes...

Anyway :) Merged! I'll get some more bits done on the back of this

**Comment by DanAtkinson** [comment]
Thanks very much for doing this. It's really appreciated! :D :+1:

**Pull request merged**
